import "./globals.css";
import Wrapper from "@/components/Layout/Wrapper";
import "../../public/assets/utils.css";
import "../../public/assets/app.css";
import Loader from "@/components/Common/Loader";
import CustomScripts from "@/Services/CustomScripts";
import Footer from "@/components/Layout/Footer";
import CookiesConsent from "@/components/Common/CookiesConsent";
import Navbar from "@/components/Layout/Navbar";
import ContactFormModal from "@/components/Common/Modals/ContactFormModal";
import CartModal from "@/components/Common/Modals/CartModal";
import QuoteViewModal from "@/components/Common/Modals/QuoteViewModal";
import QuoteConfirmedModal from "@/components/Common/Modals/QuoteConfirmedModal";
import StudiosFixedMenu from "@/components/Common/StudiosFixedMenu";
import {
  getCreateAccountModalContent,
  getForgotPasswordModalContent,
  getLoginModalContent,
} from "@/Services/NavbarApis";
import {
  getAddressesData,
  getFooterContent,
  getFooterLinksData,
  getSocialLinksData,
} from "@/Services/FooterApis";
import { getMarketsData } from "@/Services/HomeApis";

export const metadata = {
  title: "BPS Rentals",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const [
    loginModalContent,
    createAccountModalContent,
    forgotPasswordModalContent,
    footerContent,
    footerLinksData,
    socialLinksData,
    addressesData,
    marketsData,
  ] = await Promise.all([
    getLoginModalContent(),
    getCreateAccountModalContent(),
    getForgotPasswordModalContent(),
    getFooterContent(),
    getFooterLinksData(),
    getSocialLinksData(),
    getAddressesData(),
    getMarketsData(),
  ]);
  return (
    <>
      <CustomScripts />
      <html lang="en">
        <body
          data-scroll-direction="initial"
          data-search-container
          data-load="first-loading"
          className="overflow-hidden"
        >
          <span className="initScript d-none"></span>
          <span className="closeModals d-none"></span>
          <span className="initializeCanvas d-none"></span>
          <span className="home d-none"></span>
          <span className="updateWatched d-none"></span>
          <span className="galleryLightBox d-none"></span>
          <span className="collections d-none"></span>
          <span className="products d-none"></span>
          <span className="productsPost d-none"></span>
          <span className="cartPage d-none"></span>
          <span className="myAccount d-none"></span>
          <span className="savedProducts d-none"></span>
          <span className="quotesHistory d-none"></span>
          <span className="changePassword d-none"></span>
          <span className="galleryImages d-none"></span>
          <span className="addToCart d-none"></span>
          <span className="modalLoad d-none"></span>
          <span className="loadMore d-none"></span>
          <span className="updateWatchedTrigger d-none"></span>
          <span className="triggerSplitWordAnimation d-none"></span>
          <span className="stickyAnimationTrigger d-none"></span>
          <Loader />
          <Navbar
            loginModalContent={loginModalContent}
            createAccountModalContent={createAccountModalContent}
            forgotPasswordModalContent={forgotPasswordModalContent}
            marketsData={marketsData}
          />
          <CookiesConsent />
          <Wrapper>
            <main>{children}</main>
            <Footer
              footerContent={footerContent}
              footerLinksData={footerLinksData}
              socialLinksData={socialLinksData}
              addressesData={addressesData}
            />
          </Wrapper>
          <StudiosFixedMenu />
          <CartModal />
          <ContactFormModal />
          <QuoteViewModal />
          <QuoteConfirmedModal />
        </body>
      </html>
    </>
  );
}
